import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// import Header from "./Header";


const ubuntu = Ubuntu({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable}  antialiased`}>
        {/* <Header /> */}
        {children}

      </body>
    </html>
  );
}
